### ISSUE TITLE
diffs look weird with indent-blankline.nvim active

### ISSUE THREAD

**Issue by bjornevik** [marko-cerovac/material.nvim#108]
Hi, the changes following #107 have made diffs look a bit weird if you have indent-blankline.nvim active.

c1f4553
![image](https://user-images.githubusercontent.com/5864000/185857172-cb030fd5-9875-4887-9486-b1a94e9024c9.png)

HEAD
![image](https://user-images.githubusercontent.com/5864000/185857319-f6c4739d-3124-4d39-a564-161f4356426c.png)

HEAD with indent-blankline.nvim and listchars disabled
![image](https://user-images.githubusercontent.com/5864000/185858222-33222ff2-c7f9-4f25-9ad3-5ee2f3a670a6.png)

Granted, am unsure if this is something that can be changed here, but I thought I'd open an issue nonetheless 😄

**Comment by marko-cerovac** [comment]
@bjornevik I've looked at this today and the issue doesn't stem from indentline.
The issue is that the ```listchars``` option has the default foreground value of ```#464B5D``` and diff reverses the foreground and background color, so that color gets applied to the background. I don't know why this is the case, but neovim overrides the diff highlight in order to display the listchars. In any case, this is a difficult situation as I am forced to decide between a nice and clean looking diff mode and compatibility with the listchars option. For now, the fix would be to ```:set nolist``` when you enter diff mode.
