### ISSUE TITLE
Colors overwrite feature

### ISSUE THREAD

**Issue by cesarFuhr** [marko-cerovac/material.nvim#109]
Hey I saw that you have a TODO comment [here](https://github.com/marko-cerovac/material.nvim/blob/901dae9cc3a0afafb6b86fabd2a10235d5865f2f/lua/material/config.lua#L40).

Are you planing to work on that soon? if not, can I try to implement it and issue a PR?

Thanks!
Love the theme :heart:

**Comment by marko-cerovac** [comment]
Well, I was planing on implementing it (and despite the TODO comment, this feature already works), but I've realized that it's a very non-intuitive way to go about doing this. So the feature exists technically, I just don't want people to use it because it adds unnecessary complexity to the theme.
Instead of doing it like this (which is the way you would do it with the custom_colors option) :
```lua
require("material").setup {
   custom_colors = {
        my_blue = "#0000FF",
        my_red= "#FF0000",
    },
    custom_highlights = {
        Function = { fg = "my_blue", bg = "my_red" }
   }
}
```

It is much cleaner for the user and for the plugin to do it like this:
```lua
-- This returns a table with the colors that the theme uses
local colors = require("material.colors")

-- Some user defined colors
local my_red = "#FF0000"
local my_blue = "#0000FF"

require("material").setup {
    custom_highlights = {
        Function = { fg = my_blue, bg = my_red }, -- Using user defined red and blue
        LineNr = { fg = colors.blue, bg = colors.red }, -- Using the theme defined red and blue
    }
}
```

I will be removing the custom_colors feature soon and updating the documentation with a code example similar to this one.
Thank for the support and interest in the plugin. :heart: :heart:

**Comment by cesarFuhr** [comment]
Gotcha, but what I really wanted is to change the background color... 
If I try to do that with the `custom_highlights` option I will have to find each one of the highlights and overwrite them one by one. if I had access to `custom_color` I could do that with a single color overwrite.

Is there any other way to do that?

**Comment by marko-cerovac** [comment]
Actually, that's a pretty good use case. I guess I won't be removing it. 
For now, you can use the custom_colors table like this:
```lua
custom_colors = {
    bg = "#color",  -- standard background color
    bg_alt = "#color", -- background color for contrasted windows
}
```

Btw, if you use telescope.nvim, I've just added a cool little function to select styles, so check it out in the README 😉

**Comment by cesarFuhr** [comment]
Ok, that works!
Thanks, for some reason I hadn't found the code that loaded the custom colors before.

:+1:
