### ISSUE TITLE
Custom Highlights are all Cleared

### ISSUE THREAD

**Issue by ameddin73** [marko-cerovac/material.nvim#130]
Updated plugin recently, and all my custom highlights are `cleared` now. If I remove the highlight group from `custom_highlights` it goes back to the default. Any idea what might be going wrong?
![image](https://user-images.githubusercontent.com/6893820/197304233-9433e603-c64a-4c34-897d-e6504f9ee7b9.png)
![image](https://user-images.githubusercontent.com/6893820/197304266-4360ce00-a4b0-4a28-99a5-4d15738c5f13.png)

**Comment by marko-cerovac** [comment]
Oh, I see the issue.
The colors aren't just in the colors table. So you can't just use ```colors.green``` for example.
The new colors table is further divided into sub-tables.  You can see them in **lua/material/colors/init.lua**.
It goes something like this:
```lua
material.colors = {
    main = {
    -- main colors like green, red, cyan ...
    },
    editor = {
    -- editor colors like fg, bg, border ...
    },
    syntax = {
    -- syntax colors like string, variable ...
    },
    git = {
    -- git colors: added, removed and modified
    },
    lsp = {
   -- lsp colors: error, warning, info and hint
    },
    backgrounds = {
    -- various backgrounds
    }
}
}
```
So instead of ```colors.green```, you now use ```colors.main.green```, and instead of ```colors.bg```, you now use ```colors.editor.bg```, and so on...

**Comment by ameddin73** [comment]
Great catch. That fixed it, thansk!
