### ISSUE TITLE
Automatic enabling of plugin support

### ISSUE THREAD

**Issue by nkakouros** [marko-cerovac/material.nvim#184]
Theming for compatible plugins currently has to be explicitly enabled in the config via the `plugins` list. It would be great if the theme detected the installed plugins and just themed them. 

Alternatively, if I enabled them all, would there be an issue if I don't have some plugins installed, e.g. performance issues?

**Comment by marko-cerovac** [comment]
So far, i'm not aware of an easy way to implement this detection because different plugin managers have different ways of storing and loading plugins. Another issue is the fact that modern plugin managers support lazy loading which makes it very hard to detect which plugins the user already has. Also even if you set the highlights for a plugin that gets loaded later on, sometimes the plugin overrides the highlights when it gets loaded. It can get really messy.
This theme supports a fair amount of plugins and that is a lot of highlight groups to set. There are about 400 or 500 highlights to set if you enable support for every plugin (which most people don't use). It is easier to pick the plugins that you are going to use and  enable support for them. I't is not a problem if you enable every plugin and the performance impact will be barely noticable. But I like to keep things clean and plan ahead. As the plugin ecosystem keeps growing, we could have a couple thousand highlights to set in the future. This way, things remain clean.

**Comment by nkakouros** [comment]
This is indeed hard to support. Thanks for clarifying. I am using a few dozen plugins and I play around with new plugins occasionally. It is hard to keep all the bits that reference other bits in `init.lua` up to date (like the `plugins` setting that should reference installed plugins only). Also, it is hard to keep up to date with new plugin support in material and a plugin that I use may be unthemed until I realize a year later that it is supported. If there is no way around this, let's close this issue.

**Comment by marko-cerovac** [comment]
I'll see what I can do to make this easier to track. For now, when you update material.nvim and see the commits made, there will usually be a commit message along the lines of ```added support for flash.nvim``` for example. Although I do plan on making a system that notifies the user when a new plugin gets supported.
