### ISSUE TITLE
low visual difference on pyton code

### ISSUE THREAD

**Issue by JoseConseco** [marko-cerovac/material.nvim#23]
Here is dark version of material theme on my python code:
![image](https://user-images.githubusercontent.com/13521338/117878249-d94d4580-b2a5-11eb-8ae6-11d596d450a7.png)

The variables  names are almost same color as comments.   I think bumping brightness of variables by 30% could help differentiate them from comments. Thanks for great theme

**Comment by marko-cerovac** [comment]
Well, I was trying to follow the original material theme [pallete](https://www.material-theme.com/docs/reference/color-palette/) as much as I could because I want the theme to be as authentic and close to the original as possible. I'll look into making the variables lighter to be more readable. There is an option to fix this right now. You can set g:material_variable_color to some lighter value to make it stand out more.
You can try for example:
```vim
"Vim-Script
let g:material_variable_color="#BOBEC5"
```

```lua
--Lua
vim.g.material_variable_color="#BOBEC5"
```
This way, the variables will have the #BOBEC5 color or any other hex color value that you set. This option was added exactly for this purpose. To make the variables stand out more if you find them harder to see.

**Comment by JoseConseco** [comment]
thx. That seem to fixed the issue for me
