### ISSUE TITLE
Grubox Material themes

### ISSUE THREAD

**Issue by leiserfg** [marko-cerovac/material.nvim#29]
Could you add <https://github.com/sainnhe/gruvbox-material>, please?

**Comment by marko-cerovac** [comment]
Sorry, but that would be nearly impossible to do for this colorscheme. You see, the five variations of the theme (darker, lighter, palenight, oceanic and deep ocean) aren't separate themes, they are one theme. The only difference is, when you select one style, some color values like the background color get a different value (eg. white for lighter variant and gray for palenight), but the rest of the theme stays the same. If you look closely, even when the style changes, the function names are always blue, strings are always green, variable names are always gray and so on... That's why material isn't 5 different themes, but just one theme that can change it's style. The problem is that Gruvbox uses a completely different set of highlights (function names are green,variables are white, if and while statements are red etc.). This means that I would have to make completely new colorscheme to make this work and the code would be huge and messy. Also the darker variant is meant to be a material version of the Gruvbox theme anyway
