### ISSUE TITLE
Underline should not change color

### ISSUE THREAD

**Issue by folke** [marko-cerovac/material.nvim#5]
Thanks for the fix with the lsp colors!

The addition of the underline is great, but you should probably not change the colors in that group. Just add an underline style, like `gui=undercurl`.

How it looks right now:
![image](https://user-images.githubusercontent.com/292349/114395459-3f349900-9b51-11eb-84dd-38e8f27e9e15.png)

With just underline set (from zephyr theme)
![image](https://user-images.githubusercontent.com/292349/114395482-478cd400-9b51-11eb-9163-b855230bedef.png)

**Comment by marko-cerovac** [comment]
I have tried to make that exact thing work this morning and sadly failed...
The problem is that when the foreground is left to NONE, the underline is also left in the original color of the variable (eg. blue for an error in a function call)
This should be done by setting the foreground to NONE and guisp to the desired underline color(eg. red for an error).
The plugin that I'm using to write this colorscheme currently doesn't support setting guisp.
I've opened up an issue to see if there is any way to add this or bypass it.
As soon as it gets resolved, I'll implement it immediately.

**Comment by folke** [comment]
@marko-cerovac that would be awesome. Great colorscheme!

**Comment by marko-cerovac** [comment]
@folke I've installed the Zephyr theme and noticed that the same issue occurs with it, just like with my theme. That is: when I set the LspDiagnisticsUnderline variables to have an undercurl of a certain color, the color doesn't get registered (stays the same as the text color) and I can't get the undercurl to show up (when I set gui to undercurl, I just get a straight underline). This might just be an issue with my personal setup. I've managed to work around and set the LspDiagnosticsUnderline just like in the Zephyr theme and removed the material_lsp_underline option but it still doesn't work right in my setup

Can you please let me know if it's working correctly for you so that I know where to look for a solution next ?

**Comment by marko-cerovac** [comment]
![Uploading 2021-04-13-20_30_18-screenshot.png…]()

**Comment by marko-cerovac** [comment]
![Uploading 2021-04-13-20_30_18-screenshot.png…]()

**Comment by folke** [comment]
The weird thing is that even with the zephyr theme, I only get a small portion of the text having an underline.
![image](https://user-images.githubusercontent.com/292349/114604926-5efdb700-9c4e-11eb-9f0b-b4a9197cd2f4.png)

Same for material:
![image](https://user-images.githubusercontent.com/292349/114604950-6a50e280-9c4e-11eb-824a-3e3ccd235e95.png)

I've been messing around with my config today, but since you also don't seem to see the underline, there might be an issue with lsp-config or something that was pushed somewhere today?

Either way, great for adding this to the theme!

**Comment by marko-cerovac** [comment]
Thanks, I'm glad it's working at least to some degree

**Comment by folke** [comment]
for some reason, my typescript lsp server stopped working. Looking into it. Definitely an issue on my end. That little underline was coming from efm, so the underline changes probably work as expected.

**Comment by folke** [comment]
The lsp server works again and underline shows how it should. Thanks again, looks great!

![image](https://user-images.githubusercontent.com/292349/114609819-0d582b00-9c54-11eb-986a-f07267ec0de5.png)

**Comment by marko-cerovac** [comment]
Okay then, I guess that's great news. Now I've got to figure out where my config is messed because I'm still getting straight lines without color.
