### ISSUE TITLE
clarify setup function and how to remove warnings

### ISSUE THREAD

**Issue by matu3ba** [marko-cerovac/material.nvim#55]
1. The README still shows usage of `set()`[here](https://github.com/marko-cerovac/material.nvim#-usage).
2. Changing it to `setup()` did not remove warnings. So `  use { 'marko-cerovac/material.nvim', config = function() require('material').setup() end } --<l>m` did not make message go away.
3. Why is `vim.cmd[[colorscheme material]]` required? Any technical reasons? Toggling colors also enables them, ie with `map('n', '<leader>m', [[<cmd>lua require('material.functions').toggle_style()<CR>]], opts)` everything works, so I am surprised that I need an additonal config option.

**Comment by marko-cerovac** [comment]
Well, since the theme moved to a config function, the set() function was giving me some issues, so i had to remove it. If you want to use the default settings for the theme, you don't even need to call the setup() function. You can just use ```colorscheme material```. I forgot to update the help docs and remove the the set() function. It will be removed tomorrow.

**Comment by tomaskallup** [comment]
I don't have the `set` function in my config, but I still get the warning, which is annoying.

![image](https://user-images.githubusercontent.com/26621166/133257687-77fbf3cf-3694-4fed-833f-01f3ff451744.png)

**Comment by tomaskallup** [comment]
Nevermind, moving the `vim.g.material_borders` into the `borders` inside `setup` function seems to have removed the warning.

It would be nice to have this nicely written, like: `Make sure to move all your custom settings into the setup function (no global variables) to remove the warning.`

**Comment by marko-cerovac** [comment]
Okay, I've added another line to the warning for clarification. The issue is that, this is a big change in the way you set up the theme. The setup function example is too big to just put in a warning message. That's why it's all detailed in the help documentation. I was hoping that people would read the warning message, and go to ```:help material.nvim-configuration```. There, you can find the full setup function and there is even an example of what a nice config would look like that you can just copy and paste. I was planing to keep the warning message there for about a month and then remove it after most users have seen it (hopefully).

**Comment by tomaskallup** [comment]
> Okay, I've added another line to the warning for clarification. The issue is that, this is a big change in the way you set up the theme. The setup function example is too big to just put in a warning message. That's why it's all detailed in the help documentation. I was hoping that people would read the warning message, and go to `:help material.nvim-configuration`. There, you can find the full setup function and there is even an example of what a nice config would look like that you can just copy and paste. I was planing to keep the warning message there for about a month and then remove it after most users have seen it (hopefully).

This isn't about the `setup` function tho. I've read the `:help material.nvim-configuration`, but it's missing the important piece of information I mentioned. I believe it should clearly state that you should remove all the old `vim.g` related to `material.nvim` and move them to the setup function. The provided example configuration in there is nice, it just didn't hit me that I had to remove the old variables.

**Comment by marko-cerovac** [comment]
I intended for the warning to be there temporarily, just long enough for the users to migrate to the new setup function. Well, a month has passed since I implemented this change, so I think the warning isn't useful anymore. That's why I removed it completely. So it doesn't matter now anyways. If there's anyone that's just updating the theme now, their plugin won't break, it will just fall back to the default settings.
