### ISSUE TITLE
Higher contrast for self keyword (Python) palenight theme

### ISSUE THREAD

**Issue by equalis3r** [marko-cerovac/material.nvim#60]
Thank you for such great colorscheme. I would like to ask whether it is possible to make the self keyword in Python a little bit more differentiable? Self keyword has the same color as parameters so it's quite difficult to differentiate between a function and a class method.

**Comment by marko-cerovac** [comment]
@equalis3r  Of course, I'm working on it. Can you please post a random screenshot of the problem, so that I can see exactly which highlight groups I need to change.

**Comment by equalis3r** [comment]
@marko-cerovac Thanks for your fast response. Below is a screenshot. I'm also using treesitter but the self keyword still has the same color as the attributes of the class.

![2021-10-02_20-10-1633199883](https://user-images.githubusercontent.com/12251943/135728223-ef8eaf7d-cba2-4315-b161-b50320eefea0.jpg)

**Comment by marko-cerovac** [comment]
Thanks for the screenshot, It made things a lot easier. The issue seems to be with treesitter. Both the 'self' keyword and the parameters fall under the same highlight group called TSField. This means that they can't be separated. If you open material.nvim/lua/material/theme.lua and go to the line 252, you can change the value to some other color and you will see that both the keyword and the parameter change.

When you are trying to manage 5 styles of a colorscheme and need to get them to be perfect, many issues and flaws like this pop up. That is why I created an option for the user to overwrite any highlight that they don't like.
If you find the color really difficult to work with, I suggest adding something like this to your theme config
```lua
require('material').setup({
    custom_highlights = {
        TSField = { fg = '#F07178' } -- This will make them red
    }
})
```

**Comment by equalis3r** [comment]
You're right. I will keep using the theme without modifying though. Changing fg to red is not to my liking but there is always an option. Thanks again for your support. :+1:
