### ISSUE TITLE
When I setting constract background for dap-ui, the highlight of variable is changed.

### ISSUE THREAD

**Issue by cstsunfu** [marko-cerovac/material.nvim#94]
![image](https://user-images.githubusercontent.com/24812659/167272803-542a8fe6-a3e6-4a8d-93e1-9b2513241241.png)
![image](https://user-images.githubusercontent.com/24812659/167272846-6cfb2af2-4457-4d8b-9849-b3cdfc8d0007.png)

The variable highlight is not controlled by DAP-UI, so I think the variable gray background is from `Material`. 
I want to know, how should I clear the highlight of this part?

**Comment by marko-cerovac** [comment]
The issue is that when you give contrast to the dap-ui windows, it switches the ```Normal``` highlight group for a custom highlight group. But these variables are still linking to the original ```Normal``` group. This is something that is difficult to solve, but I will try. I will most likely need to submit a pull request to dap-ui. For now, a good solution to use is this:
```lua
require("material").setup({
  -- ... your config

  custom_highlights = {
    DapUIValue = { link = "NormalContrast" },
    DapUIVariable = { link = "NormalContrast" },
    DapUIFrameName = { link = "NormalContrast" },
  },
})
```

**Comment by cstsunfu** [comment]
Thanks,  this solution works.
